name: Backup
on:
  schedule:
    - cron: "10 10 1-31/2 * *"
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check and release
        run: |
            mkdir cnip
            cd cnip
            curl -s https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt |sed -e 's/^/add address=/g' -e 's/$/ list=CNIP/g'>1.rsc
            curl -s https://www.ipdeny.com/ipblocks/data/countries/cn.zone |sed -e '/^#.*/d' -e 's/^/add address=/g' -e 's/$/ list=CNIP/g'>2.rsc
            curl -s https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt |sed -e '/^#.*/d' -e 's/^/add address=/g' -e 's/$/ list=CNIP/g'>3.rsc
            curl -s http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest | awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' |sed -e '/^#.*/d' -e 's/^/add address=/g' -e 's/$/ list=CNIP/g'>4.rsc
            curl -s http://www.iwik.org/ipcountry/CN.cidr |sed -e 's/^/add address=/g' -e 's/$/ list=CNIP/g'| awk 'NR>1'>>5.rsc
            curl -s https://ispip.clang.cn/all_cn.txt |sed -e '/^#.*/d' -e 's/^/add address=/g' -e 's/$/ list=CNIP/g'>6.rsc
            curl -s https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute.txt |sed -e 's/^/add address=/g' -e 's/$/ list=CNIP/g'>7.rsc
            sort 1.rsc 2.rsc 3.rsc 4.rsc 5.rsc 6.rsc 7.rsc |awk ' !x[$0]++'|sed -e $'1i\\\n/ip firewall address-list' -e $'1i\\\nremove [/ip firewall address-list find list=CNIP]' -e $'1i\\\nadd address=192.168.0.0/16 list=CNIP comment=private-network'>../cnip.rsc
            rm -rf 1.rsc 2.rsc 3.rsc 4.rsc 5.rsc 6.rsc 7.rsc
            cd ../
            mkdir -p .github/workflows
            wget -qO .github/workflows/Backup.yml https://github.com/${{ github.repository }}/raw/main/.github/workflows/Backup.yml &> /dev/null
            git config --global init.defaultBranch main
            git init
            git add .
            git config user.name "Scaleya"
            git config user.email "61817665+Scaleya@users.noreply.github.com"
            git commit -m "new changes"
            git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git push origin main --force
